name: Testing with rabbitmq

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: node:lts
      env:
        CI: true

    # services:
    #   rabbit:
    #     image: rabbitmq:alpine
    #     ports:
    #       - 5672:5672

    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        run: npm install

      - name: lint source code
        run: npm run lint

      # - name: test
      #   run: npm run coverage
      #   env:
      #     rabbit_url: amqp://guest:guest@rabbit:${{ job.services.rabbit.ports[5672] }}/
